#!/bin/bash

# build the devuser image
GROUPID=`id -g` USERID=`id -u` bash -c 'cat devuser/Dockerfile | envsubst | sudo docker build -t local/devuser:base -'
sudo docker build -t local/ruby:dev rubydev/
