# ubuntu
# bashrc

export TERM=screen-256color

export DOTFILES=$HOME/.dotfiles

. ~/.bash_aliases
. $DOTFILES/bash/git.completion.bash
. $DOTFILES/bash/gitbashrc

# setup my bin
export PATH="$HOME/.dotfiles/bin:$PATH"


# go path
export PATH=$PATH:$GOPATH/bin

# direnv
eval "$(direnv hook bash)"
